---

# Haskish, but keyserver param doesn't work and I cannot pass recv-keys option to GPG
- name: Tests if Docker repository key present 
  apt_key: id=A88D21E9 keyring=/etc/apt/trusted.gpg state=present
  ignore_errors: True
  register: apt_result
  when: ansible_os_family == "Debian"

- name: Install Docker repository key
  command: apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 36A1D7869245C8950F966E92D8576A8BA88D21E9
  when: ansible_os_family == "Debian" and apt_result|changed

- name: Add docker repository
  apt_repository: repo='deb http://get.docker.io/ubuntu docker main' state=present update_cache=yes
  when: ansible_os_family == "Debian"

- name: Instal Docker
  apt: name=lxc-docker state=present
  when: ansible_os_family == "Debian"

- name: Setup default hosts
  template: src=hosts.j2 dest=/etc/ansible/hosts

# Further configuration after installation of Docker.
# See http://docs.docker.io/en/latest/installation/ubuntulinux/

# TODO: need Ansible 1.6

#- name: Configure Linux kernel to support memory and swap accounting
#  replace: dest=/etc/default/grub regexp='^GRUB_CMDLINE_LINUX=""' replace='GRUB_CMDLINE_LINUX="cgroup_enable=memory swapaccount=1"' backup=yes owner=root group=root mode=0644
#  register: grub_file
#  when: ansible_os_family == "Debian"

#- name: Update Grub if necessary
#  command: update-grub
#  when: ansible_os_family == "Debian" and grub_file|changed

#- name: Configure Docker to use a well known DNS server
#  replace: "dest=/etc/default/docker regexp='^#DOCKER_OPTS=' replace='DOCKER_OPTS=\"-dns 8.8.8.8 -dns 8.8.4.4\"' owner=root group=root mode=0644"
#  register: docker_config

#- debug: msg="{{docker_config}}"
#
#- name: Restart Docker
#  service: name=docker state=restarted
#  when: docker_config|changed
